/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AnimationText: typeof import('./src/components/AnimationText.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Header2: typeof import('./src/components/Header-2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Projects: typeof import('./src/components/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
  }
}
